add wave signal_in
add wave scm1_p
add wave scm1_n
add wave scm2_p
add wave scm2_n
add wave comp_out
add wave phi1
add wave phi2
add wave ctrl1
add wave ctrl1_bar
add wave ctrl2
add wave ctrl2_bar
add wave s
add wave DATA
add wave data_en
add wave sincFilter1:acc1
add wave sincFilter1:acc2
add wave sincFilter1:acc3
add wave sincFilter1:diff1
add wave sincFilter1:diff2
add wave sincFilter1:diff3
run -all